//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPP_Project.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Comments
    {
        public int IdComment { get; set; }
        public int IdStudent { get; set; }
        public int IdCourse { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
        public int State { get; set; }
    }
}
