//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPP_Project.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Company
    {
        public int IdCompany { get; set; }
        public int IdUser { get; set; }
        public int UserType { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string EmailUser { get; set; }
        public string EmailCompany { get; set; }
        public string Website { get; set; }
        [System.Web.Mvc.AllowHtml]
        public string Description { get; set; }
    }
}
