//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPP_Project.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Course
    {
        public int IdCourse { get; set; }
        public int IdTeacher { get; set; }
        public int IdCompany { get; set; }
        public string Name { get; set; }
        public int Lectures { get; set; }
        public int State { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
