//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPP_Project.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZPPEntities_NoDb : DbContext
    {
        public ZPPEntities_NoDb()
            : base("name=ZPPEntities_NoDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_Attendance> V_Attendance { get; set; }
        public virtual DbSet<V_Comments> V_Comments { get; set; }
        public virtual DbSet<V_Companies> V_Companies { get; set; }
        public virtual DbSet<V_Courses> V_Courses { get; set; }
        public virtual DbSet<V_Grades> V_Grades { get; set; }
        public virtual DbSet<V_Groups> V_Groups { get; set; }
        public virtual DbSet<V_Lectures> V_Lectures { get; set; }
        public virtual DbSet<V_Students> V_Students { get; set; }
        public virtual DbSet<V_Teachers> V_Teachers { get; set; }
        public virtual DbSet<V_UserInfo> V_UserInfo { get; set; }
        public virtual DbSet<V_UserLogin> V_UserLogin { get; set; }
    }
}
