//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPP_Project.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZPPEntities_NoDb : DbContext
    {
        public ZPPEntities_NoDb()
            : base("name=ZPPEntities_NoDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_Attendance> V_Attendance { get; set; }
        public virtual DbSet<V_Comment> V_Comment { get; set; }
        public virtual DbSet<V_Company> V_Company { get; set; }
        public virtual DbSet<V_Course> V_Course { get; set; }
        public virtual DbSet<V_Grade> V_Grade { get; set; }
        public virtual DbSet<V_Group> V_Group { get; set; }
        public virtual DbSet<V_Lecture> V_Lecture { get; set; }
        public virtual DbSet<V_Student> V_Student { get; set; }
        public virtual DbSet<V_Teacher> V_Teacher { get; set; }
        public virtual DbSet<V_UserInfo> V_UserInfo { get; set; }
        public virtual DbSet<V_UserLogin> V_UserLogin { get; set; }
        public virtual DbSet<V_CompanyInfo> V_CompanyInfo { get; set; }
        public virtual DbSet<V_StudentInfo> V_StudentInfo { get; set; }
        public virtual DbSet<V_TeacherInfo> V_TeacherInfo { get; set; }
        public virtual DbSet<SL_UserType> SL_UserType { get; set; }
        public virtual DbSet<SL_CommentState> SL_CommentState { get; set; }
        public virtual DbSet<SL_CourseStates> SL_CourseStates { get; set; }
    }
}
